import streamlit as st
import os
from utils.gemini_client import generate_summary
from database.db_manager import get_setting
from utils.theme_manager import inject_theme, load_branding

st.set_page_config(page_title="AI Summarizer - EduAI", page_icon="📝", layout="wide")

inject_theme()
load_branding()

if "api_key" not in st.session_state or not st.session_state.api_key:
    db_key = get_setting("api_key", "")
    if db_key:
        st.session_state.api_key = db_key
    else:
        st.session_state.api_key = os.getenv("GEMINI_API_KEY", "")

if "cached_summaries" not in st.session_state:
    st.session_state.cached_summaries = {}

active_file = st.session_state.get("current_file", "")
api_key = st.session_state.get("api_key", "")

if not active_file:
    st.warning("Please upload a study material PDF/TXT file first in the Study Material page.")
elif not api_key:
    st.warning("Please configure your Gemini API Key in the Settings page to generate summaries.")
else:
    extracted_txt_path = os.path.join("uploads", f"{active_file}_extracted.txt")
    if not os.path.exists(extracted_txt_path):
        st.error("Extracted text not found. Please re-process your study material.")
    else:
        with open(extracted_txt_path, "r", encoding="utf-8") as f:
            document_text = f.read()
            
        col1, col2 = st.columns([3, 1])
        with col1:
            st.markdown(f"""
            <div style='margin-bottom: 20px;'>
                <p style="font-size:18px;font-weight:600;margin:0 0 4px">AI summary — {active_file.split('.')[0]}</p>
                <p style="font-size:13px;color:var(--text-secondary);margin:0">Read concise summaries, bullet points, and core concepts generated by AI.</p>
            </div>
            """, unsafe_allow_html=True)
        with col2:
            st.write("")
            regenerate = st.button("🔄 Regenerate", use_container_width=True)
            
        summary_data = None
        if active_file in st.session_state.cached_summaries and not regenerate:
            summary_data = st.session_state.cached_summaries[active_file]
        else:
            with st.spinner("Analyzing text and generating summary..."):
                summary_data = generate_summary(document_text, api_key)
                if summary_data and "Error generating summary" not in summary_data.get("concise_summary", ""):
                    st.session_state.cached_summaries[active_file] = summary_data

        if summary_data:
            if "Error generating summary" in summary_data.get("concise_summary", ""):
                st.markdown(f"""
                <div class="custom-alert-danger">
                  <strong>🔑 Error</strong><br>
                  {summary_data.get('concise_summary')}
                </div>
                """, unsafe_allow_html=True)
            else:
                tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs([
                    "Bullet points", 
                    "Key concepts", 
                    "ELI10", 
                    "Summary", 
                    "Important Formulae", 
                    "Real Life Example"
                ])
                
                with tab1:
                    with st.container(border=True):
                        st.markdown("### Bullet points")
                        bullets = summary_data.get("bullet_points", [])
                        for b in bullets:
                            st.markdown(f"• {b}")
                            
                with tab2:
                    with st.container(border=True):
                        st.markdown("### Key concepts")
                        concepts = summary_data.get("key_concepts", [])
                        if concepts:
                            for c in concepts:
                                st.markdown(f"""
                                <div class="custom-alert-warning" style="margin-bottom: 12px;">
                                  <strong>{c.get('concept', 'Concept')}</strong><br>
                                  {c.get('definition', '')}
                                </div>
                                """, unsafe_allow_html=True)
                        else:
                            st.write("No concept glossary generated.")
                            
                with tab3:
                    with st.container(border=True):
                        st.markdown("### Explain Like I'm 10 (ELI10)")
                        st.write(summary_data.get("simple_analogy", ""))
                        
                with tab4:
                    with st.container(border=True):
                        st.markdown("### Core Summary")
                        st.write(summary_data.get("concise_summary", ""))
                        
                with tab5:
                    with st.container(border=True):
                        st.markdown("### Important Formulae & Rules")
                        formulae = summary_data.get("important_formulae", [])
                        if formulae:
                            for f_item in formulae:
                                st.markdown(f"• {f_item}")
                        else:
                            st.write("No specific formulae generated.")
                            
                with tab6:
                    with st.container(border=True):
                        st.markdown("### Real Life Metaphor / Example")
                        st.write(summary_data.get("real_life_example", ""))
                        
                st.write("")
                
                export_text = f"AI Summary - {active_file}\n\n"
                export_text += f"CORE SUMMARY:\n{summary_data.get('concise_summary')}\n\n"
                export_text += "BULLET POINTS:\n" + "\n".join([f"- {b}" for b in summary_data.get('bullet_points', [])]) + "\n\n"
                export_text += "KEY CONCEPTS:\n" + "\n".join([f"- {c.get('concept')}: {c.get('definition')}" for c in summary_data.get('key_concepts', [])]) + "\n\n"
                export_text += f"ELI10:\n{summary_data.get('simple_analogy')}\n\n"
                export_text += "FORMULAE/RULES:\n" + "\n".join([f"- {f_item}" for f_item in summary_data.get('important_formulae', [])]) + "\n\n"
                export_text += f"REAL LIFE EXAMPLE:\n{summary_data.get('real_life_example')}"
                
                col_exp1, col_exp2 = st.columns(2)
                with col_exp1:
                    st.download_button(
                        label="📥 Export summary (TXT)",
                        data=export_text,
                        file_name=f"Summary_{active_file.split('.')[0]}.txt",
                        mime="text/plain",
                        use_container_width=True
                    )
                with col_exp2:
                    st.code(export_text[:400] + "\n... [truncated summary for preview]", language="text")
                    st.caption("Copy the summary directly from the block above.")
